### ISSUE TITLE
Support for Poetry dependency groups

### ISSUE THREAD

**Issue by fredrikaverpil** [sinoroc/tox-poetry-dev-dependencies#25]
As originally posted in the [Poetry Discord](https://discord.com/channels/487711540787675139/487711540787675143/760726313639739412).

Poetry is about to turn 1.1 and I am super keen on the scheduled ”dependency groups” feature, scheduled for 1.2: https://github.com/python-poetry/poetry/issues/1856
I was just thinking ”out loud”... with your plugin, maybe one could define one or more groups in a specific tox testenv. What do you think about that?

Maybe something like

```ini
[testenv:qa]
add_poetry_dependency_groups = [”qa”]
commands =
    black --check
    flake8
    vulture
    pytest
```

I'm not sure how the devs ultimately intend the dependency groups too work in detail. But perhaps they will add a way to define both inclusion as well as exclusion of such groups.

It's too early for this, to be honest, but perhaps good to keep in mind that this is (hopefully) around the corner.

**Comment by sinoroc** [comment]
Thanks

Makes sense to me. I don't see anything that would speak against it. We'll keep an eye on it.
